# Generated by Django 3.1.6 on 2021-03-29 13:38

from django.db import migrations
import dynamic_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0004_auto_20210329_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=dynamic_image.fields.DynamicImageField(max_length=255, upload_to='dummy'),
        ),
    ]
