# Generated by Django 3.1.6 on 2021-04-05 06:02

import appl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0006_auto_20210401_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=appl.models.upload_image_path),
        ),
    ]
