# Generated by Django 3.1.6 on 2021-04-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0008_auto_20210415_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('water pump controller', 'water pump controller'), ('level sensor', 'level sensor'), ('light master', 'light master'), ('gsm mobile starter', 'gsm mobile starter'), ('automatic starter', 'automatic starter')], max_length=200, null=True),
        ),
    ]
