# Generated by Django 3.1.6 on 2021-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0009_auto_20210417_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='pno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
