# Generated by Django 3.1.6 on 2021-04-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0010_auto_20210422_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.product'),
        ),
    ]
