# Generated by Django 3.1.6 on 2021-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0014_auto_20210426_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_home',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('water pump controller', 'water pump controller'), ('level sensor', 'level sensor'), ('light master', 'light master'), ('gsm mobile starter', 'gsm mobile starter'), ('automatic starter', 'automatic starter')], max_length=200, null=True),
        ),
    ]
