# Generated by Django 3.1.6 on 2021-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0016_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
